[tool.black]
exclude = "build"
line-length = 80
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 80
known_first_party = ["paddle"]
skip = ["build", "__init__.py"]
extend_skip_glob = [
    # These files do not need to be formatted,
    # see .flake8 for more details
    "python/paddle/fluid/[!t]**",
    "python/paddle/fluid/tra**",
    "python/paddle/utils/gast/**",
    "python/paddle/fluid/tests/unittests/npu/**",
    "python/paddle/fluid/tests/unittests/mlu/**",
]

[tool.ruff]
exclude = [
    "./build",
    "./python/paddle/fluid/[!t]**",
    "./python/paddle/fluid/tra**",
    "./python/paddle/utils/gast/**",
    "./python/paddle/fluid/tests/unittests/npu/**",
    "./python/paddle/fluid/tests/unittests/mlu/**",
]
target-version = "py37"
select = [
    # Pyflakes
    "F401",

    # Comprehensions
    "C400",
    "C401",
    "C402",
    "C408",
    "C409",
    "C410",
    # "C411",
    # "C413",
    # "C414",
    # "C415",
    # "C416",
    # "C417",

    # Pyupgrade
    "UP001",
    "UP003",
    "UP004",
    "UP005",
    "UP007",
    "UP008",
    # "UP009",
    "UP010",
    "UP011",
    "UP012",
    "UP013",
    "UP014",
    "UP017",
    "UP018",
    "UP019",
    "UP020",
    "UP021",
    "UP022",
    "UP023",
    # "UP024",
    "UP025",
    "UP026",
    # "UP027",
    # "UP028",
    "UP029",
    # "UP030",
    # "UP031",
    # "UP032",
    "UP033",
    # "UP034",
    "UP035",
    "UP036",

    # NumPy-specific rules
    "NPY001",

    # Bugbear
    "B002",
    "B003",
    # "B004",
    # "B005",
    # "B006",
    # "B007",
    # "B008",
    "B009",
    "B010",
    "B011",
    "B012",
    "B013",
    "B014",
    # "B015",
    # "B016",
    # "B017",
    "B018",
    "B019",
    # "B020",
    "B021",
    "B022",
    # "B023",
    # "B024",
    "B025",
    # "B026",
    # "B027",
    # "B028",
    "B029",
    # "B030",
    "B032",
    # "B904",
]
unfixable = [
    "NPY001"
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"setup.py" = ["UP036"]
